version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: svelte_lansite_db
    healthcheck:
      test: pg_isready -h localhost -p 5432 -U $$POSTGRES_USER
      interval: 2s
      timeout: 5s
      retries: 15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  svelte_lansite:
    build: ./fileUpload
    container_name: svelte_lansite
    ports:
      - "8080:5173"
    depends_on:
      - postgres
    env_file:
      - ./fileUpload/.env
    volumes:
      - ./fileUpload:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
